services:
  dev-server:
    image: node:18.20-alpine
    volumes:
      - .:/app
    entrypoint: ""
    working_dir: /app
    ports:
      - 3000:3000
      - 4000:4000
    command: >
      sh -c "
        npm install
        npm run dev -- -o
      "